###
POST http://localhost:8080/wallet/transfer
Content-Type: application/json
username: testUser

{"platform_name":"platform","date":1535015447,"from":"user1","to":"user2","sum":999999999}


###
GET http://localhost:8080/wallet/balance/user2
Content-Type: application/json