version: '3.5'

services:

# DB region
  mongo:
    image: mongo
    hostname: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/